name: Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NEXT_PUBLIC_BUILD_PATH: ../build/dashboard
on:
  push:
    branches:
      - main
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_KEY }}
      - name: Build Dashboard
        run: cd frontend/dashboard && npm install && npm run build
      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_KEY }}
